config/routes.rb
Rails.application.routes.draw do
  resources :palmers
  root 'palmers#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/palmer.rb
class Palmer < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/palmers_controller.rb
class PalmersController < ApplicationController
  before_action :set_palmer, only: [:show, :edit, :update, :destroy]

  # GET /palmers
  # GET /palmers.json
  def index
    @palmers = Palmer.all
  end

  # GET /palmers/1
  # GET /palmers/1.json
  def show
  end

  # GET /palmers/new
  def new
    @palmer = Palmer.new
  end

  # GET /palmers/1/edit
  def edit
  end

  # POST /palmers
  # POST /palmers.json
  def create
    @palmer = Palmer.new(palmer_params)

    respond_to do |format|
      if @palmer.save
        format.html { redirect_to @palmer, notice: 'Palmer was successfully created.' }
        format.json { render :show, status: :created, location: @palmer }
      else
        format.html { render :new }
        format.json { render json: @palmer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /palmers/1
  # PATCH/PUT /palmers/1.json
  def update
    respond_to do |format|
      if @palmer.update(palmer_params)
        format.html { redirect_to @palmer, notice: 'Palmer was successfully updated.' }
        format.json { render :show, status: :ok, location: @palmer }
      else
        format.html { render :edit }
        format.json { render json: @palmer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /palmers/1
  # DELETE /palmers/1.json
  def destroy
    @palmer.destroy
    respond_to do |format|
      format.html { redirect_to palmers_url, notice: 'Palmer was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_palmer
      @palmer = Palmer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def palmer_params
      params.require(:palmer).permit(:name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/palmers_helper.rb
module PalmersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Palmers</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
     <!-- Compiled and minified CSS -->
   <!-- Compiled and minified CSS -->
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.98.2/css/materialize.min.css">

  <!-- Compiled and minified JavaScript -->
  <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.98.2/js/materialize.min.js"></script>
          
          
          <link href="https://fonts.googleapis.com/css?family=Playfair+Display" rel="stylesheet">
          
  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
  
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/palmers/_form.html.erb
<%= form_for(palmer) do |f| %>
  <% if palmer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(palmer.errors.count, "error") %> prohibited this palmer from being saved:</h2>

      <ul>
      <% palmer.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/palmers/edit.html.erb
<h1>Editing Palmer</h1>

<%= render 'form', palmer: @palmer %>

<%= link_to 'Show', @palmer %> |
<%= link_to 'Back', palmers_path %>

app/views/palmers/index.html.erb
<div class="topbaner">
<span>
  <h1>PHILTECK</h1>
  <h4>Your vision made possible.</h4>
  </span>
</div>

<div class="container">

  <hr>
    <h4>ABOUT</h4>

    <div class="row">
      <div class="col s12"> </div>
      <div class="col s6" id="aboutp"> 

      <p>I am a software developer who is passionate about coding. I eat, breathe, and sleep coding. I code so much when I see the word “push” on a door, I always pull first hahaha...did you get that? Aside from coding, I am a trumpetist, soccer and basketball player, I can also play tennis but you probably would be able to beat me in it.
      <br>
      My passion for programming started at an early age. By pulling electronic gadgets or toys apart, trying to understand how they work, and trying to restore them back to how it originally was. As a software developer, I like to focus on one goal at a time. I truly believe that the human mind functions better when you work step-by-step. My goal is to become a great developer that brings joy and happiness to all my clients.
      </p></div>
      <div class="col s6" id="picabout">
      <%= image_tag("phil.jpg", :size => "300x400")  %>
      </div>
    </div>
          

  <hr>
    <h4>Services</h4>
  <div class="col-s6">

  <span>
          <i class="large material-icons">stay_primary_portrait</i>
          Responsive website
  </span>
   <span>
     <i class="large material-icons">stay_primary_portrait</i>
          Responsive website
  </span>
   <span>
    <i class="large material-icons">android</i>
          Responsive website
  </span>
  

 </div>

  </div>

app/views/palmers/new.html.erb
<h1>New Palmer</h1>

<%= render 'form', palmer: @palmer %>

<%= link_to 'Back', palmers_path %>

app/views/palmers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @palmer.name %>
</p>

<%= link_to 'Edit', edit_palmer_path(@palmer) %> |
<%= link_to 'Back', palmers_path %>